version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=AStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  aspnetapp:
    build: .
    volumes:
      - ./Logs:/Logs
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mssql,1433;Database=JetStream;User ID=SA;Password=AStrong!Passw0rd;TrustServerCertificate=True;
      - CORS__AllowedOrigins=http://127.0.0.1:3000,http://localhost:3000,http://127.0.0.1:5500,http://localhost:5500
    ports:
      - "8000:8080"
    depends_on:
      - mssql
      
volumes:
  mssql_data: {}
