version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=AStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  aspnetapp:
    build: ./SkiServiceAPI
    volumes:
      - ./Logs:/Logs
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=mssql,1433;Database=JetStream;User ID=SA;Password=AStrong!Passw0rd;TrustServerCertificate=True;
    ports:
      - "8000:80"
    depends_on:
      - mssql

volumes:
  mssql_data: {}
